name = "beta"
type = "javascript"
account_id = "20f50315f067e05ad0c710e00736d61e"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./.output/public"
entry-point = "./.output"

[build]
command = "true"
upload.format = "service-worker"